export {Home} from './home/Home'
export {ErrorPages} from './error/ErrorPages'
export {Register} from './register/Register'
export {Signin} from './signin/Signin'
export {JobDetails} from './jobDetails/JobDetails'
export {JobApply} from './jobApply/JobApply'
export {MyApplications} from './myApplications/MyApplications'
export {AddJobs} from './addJobs/AddJobs'